version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tetra123 # Password to access SQL database
      - DB_NAME=fintracker
    depends_on:
      - db
    command: ["wait-for-it.sh", "db:3306", "--", "npm", "run", "dev"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tetra123
      MYSQL_DATABASE: fintracker
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
